name: Update new.txt and Generate LootLabs Link

on:
  schedule:
    - cron: '55 15 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEV_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install requests

      - name: Update new.txt and generate LootLabs link
        run: |
          python change.py ${{ secrets.DEV_KEY }} ${{ secrets.GIST_ID }} ${{ secrets.LOOTLABS_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if files exist before adding them
          if [ -f "secret.txt" ]; then
            git add secret.txt
            echo "Added secret.txt"
          else
            echo "secret.txt not found, skipping"
          fi
          
          if [ -f "lootlabs_links.json" ]; then
            git add lootlabs_links.json
            echo "Added lootlabs_links.json"
          else
            echo "lootlabs_links.json not found, skipping"
          fi
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update LootLabs link - $(date)"
            git push
            echo "Changes committed and pushed"
          fi
