name: Update new.txt and Generate LootLabs Link
on:
  schedule:
    - cron: '59 15 * * *'  # Fixed: was '55 15 * **'
  workflow_dispatch:  # Allow manual triggering
jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEV_KEY }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install requests
      - name: Update new.txt and generate LootLabs link
        run: |
          python change.py ${{ secrets.DEV_KEY }} ${{ secrets.GIST_ID }} ${{ secrets.LOOTLABS_TOKEN }}
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Pull latest changes first
          git pull origin main
          
          # Check if secret.txt exists before adding it
          if [ -f "secret.txt" ]; then
            git add secret.txt
            echo "Added secret.txt"
          else
            echo "secret.txt not found, skipping"
          fi
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update LootLabs link - $(date)"
            
            # Try to push, with retry logic
            for i in {1..3}; do
              if git push; then
                echo "Changes committed and pushed successfully"
                break
              else
                echo "Push failed, attempt $i/3. Pulling and retrying..."
                git pull origin main --rebase
                if [ $i -eq 3 ]; then
                  echo "Failed to push after 3 attempts"
                  exit 1
                fi
              fi
            done
          fi
